channels:
- bioconda
- conda-forge
- defaults
dependencies:
- biopython>=1.70
- clustalo>=1.2
- clustalw>=2.1
- gunicorn>=19.9
- mafft>=7.407
- muscle>=3.8
- pip>=18.0
- python=3.5
- t_coffee>=11.0
- pip:
  - git+git://github.com/warownia1/Slivka
