name: slivka
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.70
  - click=7.0
  - clustalo=1.2
  - clustalw=2.1
  - flask=1.0
  - frozendict=1.2
  - gunicorn=19.9
  - jinja2=2.10
  - jsonschema=2.6
  - mafft=7.407
  - markupsafe=1.0
  - mock=2.0
  - muscle=3.8
  - pip=18.0
  - python=3.5
  - pyyaml=3.13
  - requests=2.13
  - setuptools=40.4
  - simplejson=3.16
  - sqlalchemy=1.2
  - sqlite=3.28
  - t_coffee=11.0
  - werkzeug=0.15
  - pip:
    - git+git://github.com/warownia1/Slivka
