---
version: "0.3"

directory.uploads: ./media/uploads
directory.jobs: ./media/jobs
directory.logs: ./logs
directory.services: ./services

server.host: 127.0.0.1:8000
server.uploads-path: /media/uploads
server.jobs-path: /media/jobs

local-queue.host: tcp://127.0.0.1:3397

mongodb.host: 127.0.0.1:27017
mongodb.database: slivka-bio
...
