BASE_DIR: .
UPLOADS_DIR: ./media/uploads
JOBS_DIR: ./media/tasks
LOG_DIR: ./logs
SERVICES: ./services.yml

UPLOADS_URL_PATH: /media/uploads
JOBS_URL_PATH: /media/tasks

ACCEPTED_MEDIA_TYPES:
  - application/fasta
  - application/clustal
  - application/json

SECRET_KEY: =change_me=

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8000
SLIVKA_QUEUE_ADDR: 127.0.0.1:3397
MONGODB_ADDR: 127.0.0.1:27017
