package:
  name: slivka-bio
  version: 1.1

source:
  git_url: ../
  patches:
    - manage.py.patch
  folder: slivka-bio

build:
  noarch: generic
  number: 5

requirements:
  run:
    - python=3.7
    - biopython>=1.7
    - gunicorn>=19.9
    - slivka=0.6b1
    - probcons=1.12
    - mafft=7.458
    - t_coffee=13.41.0
    - muscle=3.8.1551
    - clustalw=2.1
    - clustalo=1.2.4
    - msaprobs=0.9.7
    - disembl=1.4
    - globplot=2.3
    - requests=2.23.0

