package:
  name: slivka-bio
  version: 0.8.3b0

source:
  git_url: ../
  patches:
    - manage.py.patch
  folder: slivka-bio

build:
  noarch: generic
  number: 0

requirements:
  run:
    - biopython>=1.7
    - clustalo=1.2.4
    - clustalw=2.1
    - disembl=1.4
    - globplot=2.3
    - gunicorn>=19.9
    - mafft=7.458
    - msaprobs=0.9.7
    - muscle=3.8.1551
    - probcons=1.12
    - python>=3.8
    - requests>=2.23.0
    - slivka=0.8.3b
    - t_coffee=13.41.0
    - viennarna=2.6.4

